### ISSUE TITLE
win7stage-border-issues

### ISSUE THREAD

**Issue by Thinker888** [xdsswar/shared-fx-jni-src#1]

**Comment by Thinker888** [comment]
![cd862e584450c0e36b4b70536c48390](https://github.com/xdsswar/shared-fx-jni-src/assets/89960293/2fb5772f-650c-4663-8aee-c3166044532a)

**Comment by xdsswar** [comment]
W10 and w11 only support. Thanks.

**Comment by Thinker888** [comment]
sorry, is win10OS, i said wrong. Windows 10 Professional Edition 22H2
