### ISSUE TITLE
win7:stage title javafx mouse events issues

### ISSUE THREAD

**Issue by Thinker888** [xdsswar/shared-fx-jni-src#2]
the area of title cant use fx mouse events,because win7 os mouse evente hove fx mouse events.thanks!
![111](https://github.com/xdsswar/shared-fx-jni-src/assets/89960293/4f7e765c-aaa1-408a-892e-559b0832f7d6)

**Comment by xdsswar** [comment]
This is made for w10 and w11. Sorry mate.

**Comment by Thinker888** [comment]
sorry, i said wrong, is win10 :)
