### ISSUE TITLE
win10 header issues

### ISSUE THREAD

**Issue by Thinker888** [xdsswar/shared-fx-jni-src#3]
as describe in picture,thanks.
![000](https://github.com/xdsswar/shared-fx-jni-src/assets/89960293/da601404-adc6-4cd2-90f8-9bbd4e6e3656)

**Comment by xdsswar** [comment]
If you look at the demo you will notice you need to add hitspots using the controls in the header. 
Look in the class blow how those hitspots are build and check the override of the method to return the hitspots.

https://github.com/xdsswar/shared-fx-jni-src/blob/master/demo/src/main/java/xss/it/demo/WindowDecoration.java

**Comment by Thinker888** [comment]
ok, i'm not notice the annotation actually,i'm trying,thanks.
this is great job!
How to solve top border problem and i dont add '-fx-border-with:1 0 0 0' css into header and i 'm accustomed to using css control elements instead of code

**Comment by xdsswar** [comment]
The problems is that I need to send those details to the native side and back and it gets very tricky

**Comment by xdsswar** [comment]
> ok, i'm not notice the annotation actually,i'm trying,thanks. this is great job! How to solve top border problem and i dont add '-fx-border-with:1 0 0 0' css into header and i 'm accustomed to using css control elements instead of code

With the top border I need to check, but I think is not css styleable

**Comment by Thinker888** [comment]
ok, thanks, I'm looking forward to your work.
