### ISSUE TITLE
win10 jfx tray issue

### ISSUE THREAD

**Issue by Thinker888** [xdsswar/shared-fx-jni-src#4]
after the stage closes, click on the tray to display again，can't restore after minimizing to the taskbar. thanks!

**Comment by xdsswar** [comment]
This lib is not good, I need to rebuild it using JNI since java sucks to do well the job.

**Comment by xdsswar** [comment]
you have this `constructor` in your decoration 
    /**
     * Constructs a AbstractDecoration object associated with a Stage and sets the initial showInTaskBar value.
     *
     * @param stage         The Stage associated with the AbstractDecoration.
     * @param showInTaskBar Initial value indicating whether the window should be shown in the taskbar.
     */
    public AbstractDecoration(Stage stage, boolean showInTaskBar){
        this.stage= stage;
        this.setShowInTaskBar(showInTaskBar);
        initialize();
    }
boolean showInTaskBar must be true , so when you minimize you can restore, if false then you will not see the icon

**Comment by Thinker888** [comment]
The problem still exists.

https://github.com/xdsswar/shared-fx-jni-src/assets/89960293/abb1372b-20e9-47dd-9a9a-7360f49f6ff1

I recorded a video, and the specific issues are presented in the video for your convenience in identifying the problems:The taskbar must be clicked twice to show stage and Especially after clicking the restore button, it is indeed minimized and the window cannot be displayed afterwards.

**Comment by xdsswar** [comment]
Send me thw code to reproduce it pls. Because the example I mqde works well.

**Comment by Thinker888** [comment]
This is my code, I don't know where the problem went
[code.zip](https://github.com/xdsswar/shared-fx-jni-src/files/14428458/code.zip)

**Comment by xdsswar** [comment]
New lib [Nfx-Core](https://github.com/xdsswar/nfx-lib)
